name: CI
on: push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
      - name: Install deps
        run: npm clean-install
      - name: Run Prettier
        run: npm run check-prettier
      - name: Run Typescript Compiler
        run: npm run tsc
      - name: Run Tests
        run: npm run test
